# Generated by Django 4.1.1 on 2022-10-28 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0002_alter_account_managers_account_liked_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthday',
        ),
        migrations.AddField(
            model_name='account',
            name='commented_posts',
            field=models.ManyToManyField(related_name='user_comments', to='posts.post', verbose_name='Прокомментированные публикации'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('O', 'Другое'), ('M', 'Мужской'), ('W', 'Женский')], default='Другое', max_length=100, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_info',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_likes', to='posts.post', verbose_name='Понравившиеся публикации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
